### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by fmateoc**
fix external objects array bug, which results in a missing input semaphore and no input events signalling

### CODE REVIEW

**Comment by fniephaus** [comment]
Thanks! Looks like you're using Python 3, which is now supported by `mx`. So this fixes the semaphore handling and adds Python 3 support.

**Comment by fniephaus** [comment]
Integrated via https://github.com/hpi-swa/graalsqueak/commit/fd3f635f6671d644715fb71d2520df94ddb37625, https://github.com/hpi-swa/graalsqueak/commit/eeac282ff2bf1b5b1fd37b893edd7d9b1a5f08a5, and https://github.com/hpi-swa/graalsqueak/commit/38410ad8246ac32fda42a0fdd1b12251fee000b4. Thanks!
GitHub did not detect that I've cherry picked them manually to `dev`, so I'm closing this now.

**Comment by fmateoc** [comment]
Thank you for the quick integration. I would have also liked to make a small edit to the Getting Started section of top README.md, indicating that the updater is not available on Windows, but I was not sure if there were any alternatives that should be mentioned instead

**Comment by fniephaus** [comment]
That'd be useful! @michelou has put together the following repo for Windows users:
https://github.com/michelou/graalsqueak-examples

**Comment by fniephaus** [comment]
Done: https://github.com/hpi-swa/graalsqueak/commit/7f10901d676445f269b3ef35fe2f0d8d7c90ba96

**Pull request closed without merging**
